"use client";
import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import SideNav from "~/components/Sidenav";
import Navbar from "~/components/Navbar";
import Web3Provider from "~/components/Web3Provider";
import Providers from "~/components/Providers";
import { UserProvider } from "~/components/AuthComponent";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Providers>
          <UserProvider>
            <TRPCReactProvider>
              <Web3Provider>
                <Navbar />
                <div className="container mx-auto block sm:flex sm:gap-24">
                  <SideNav />
                  {children}
                </div>
              </Web3Provider>
            </TRPCReactProvider>
          </UserProvider>
        </Providers>
      </body>
    </html>
  );
}
